SRCS += bootloader.c
SRCS += bootrom.c
SRCS += memory_pool.c
SRCS += light_stack.c
SRCS += panic.c
SRCS += assert.c
SRCS += dfu.c

SRCS += sched.c
SRCS += thread.c


INCLUDES += $(KERNEL_DIR)/include/
